routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::post('/save', 'HomeController@save')->name('backlogItemSave'); //Les 2
Route::delete('/removebli', 'homeController@removebli');
Route::get('/planning','PlanningController@index')->name('planning');
Route::post('/planning','PlanningController@store')->name('planningstore');
Route::delete('/deleteplanning','PlanningController@deleteplanning');

Auth::routes();

Route::resource('project', 'ProjectController');

app/BacklogItem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BacklogItem extends Model
{
    public function planning()
    {
        return $this->belongsTo(Planning::class);
    }
    public function project()
    {
        return $this->belongsTo(Project::class);
    }
}

app/Planning.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Planning extends Model
{
    public function backlog_items()
    {
        return $this->hasMany(BacklogItem::class);
    }
}

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    public function backlog_items()
    {
        return $this->hasMany(BacklogItem::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class)->using(ProjectUser::class);
    }
}

app/ProjectUser.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Relations\Pivot;

class ProjectUser extends Pivot
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function projects()
    {
        return $this->belongsToMany(Project::class)->using(ProjectUser::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\BacklogItemCreateRequest;
use Illuminate\Http\Request;
use App\BacklogItem;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {

//        $backlogItems = User::paginate(15);
//        $events = Events::paginate(15);
//
//        return view('adminPanel')->with(['users' => $users, 'events' => $events]);

        $backlogItems = BacklogItem::paginate(6);
//        dd($backlogItems);
        return view('home' , compact('backlogItems'));
    }

    public function save(BacklogItemCreateRequest $request) //Les 2
    {
        $data = $request->validated();
        $backlogItem = new BacklogItem();
        $backlogItem->role = $data['role'];
        $backlogItem->activity = $data['activity'];
        $backlogItem->story_points = $data['story_points'];

        $backlogItem->save();

        return redirect()->back();
    }
    public function removebli(Request $request)
    {

        $backlogItems = BacklogItem::findOrFail($request->id);
        $backlogItems->delete();

        return redirect('/home');
    }
}

app/Http/Controllers/PlanningController.php
<?php

namespace App\Http\Controllers;

use App\Planning;
use Illuminate\Http\Request;


class PlanningController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $planning = Planning::all();
        return view('planning', compact('planning'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $planning = new Planning();

        $planning->id = $request->id;
        $planning->description = $request->description;
        $planning->save();

        return redirect()->route('planning');
    }

        public function deleteplanning(Request $request)
    {

        $planning = Planning::findOrFail($request->id);
        $planning->delete();

        return redirect('/planning');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProjectCreateRequest;
use App\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $projects = Project::paginate(6);
        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        return view('project.create', compact('projects'));
        return view('project.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        return request()->all();
//        return request('title');

        $project = new Project;

        $project->title = $request->title;
        $project->description = $request->description;
        $project->deadline= $request->deadline;
        $project->save();

        return redirect()->route('project.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }

    public function save(ProjectCreateRequest $request)
    {
        $data = $request->validated();
        $projects = new Project();
        $projects->title = $data['title'];
        $projects->description = $data['description'];
        $projects->deadline = $data['deadline'];

        $projects->save();

        return redirect()->back();
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content'){{--create backlog item --}}
<div class="container text-center"><h3>Voeg een backlog item toe</h3></div>
<div class="row mt-5 justify-content-center">
    <div class="col-6">
        <div class="card">
            <form action="{{ route('backlogItemSave') }}" method="post">
                @csrf
                <div class="card-header">
                    Als <input type="text" name="role" placeholder="admin" required>
                    wil ik  <input type="text" name="activity" placeholder="story" required>
                </div>
                <div class="card-body">
                    Story points: <input type="number" name="story_points" required><br>
                    <div class="text-center"><input type="submit" value="opslaan"></div>
                </div>
            </form>
        </div>
    </div>
</div>
<br>
{{--view backlogitems on board--}}
<div class="container text-center"><h4>Backlogitems</h4></div>
<div class="container">
    <div class="row justify-content-center">
        @foreach($backlogItems as $backlogItem)
            <div class="col-4">
                <div class="card">
                    <div class="card-header">
                        Als {{ $backlogItem->role }} wil ik {{ $backlogItem->activity }}
                    </div>
                    <div class="card-body">
                        Story points: {{ $backlogItem->story_points }}
                    </div>
                    <div>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#removeModal{{$backlogItem->id}}">
                            X
                        </button>
                    </div>
                    <div class="modal" id="removeModal{{$backlogItem ->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Bevestiging</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Weet je zeker dat je <b>{{ $backlogItem ->activity }}</b> wil verwijderen?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Sluiten</button>
                                    <form action="{{url('removebli')}}" method="post">
                                        @csrf
                                        @method('delete')
                                        <input type="hidden" name="id" value="{{$backlogItem ->id}}">
                                        <input type="submit" value="Verwijder" class="btn btn-danger">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
            </div>
        @endforeach
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div id="paginationEvents" style="text-align: center">
                <div id="bar">
                {{ $backlogItems->links() }}
                </div>
            </div>
        </div>
    </div>
    {{--end backlogitems--}}
</div>
{{--end create backlogitem--}}
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>ScrumApp</title>
    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark shadow-sm">
        <div class="container">
            <a class="text-info">ScrumApp</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href={{'/'}}>Back to the app</a></li>
            <li class="breadcrumb-item active" aria-current="page">Library</li>
        </ol>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/planning.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-2">
                <h1>Sprints</h1>
                Voeg een taak toe
            </div>
            <div class="col-6">
                {{--make new sprint items--}}
                <div class="container">
                    <div class="row mt-5 justify-content-center">
                        <div class="">
                            <form action="{{ route('planningstore') }}" method="post">
                                @csrf
                                <input type="text" name="description" placeholder="Wat doet deze nieuwe taak?" required>
                                <input type="submit" value="opslaan">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
    <hr>
        {{--end make sprint items--}}
        {{--view sprint items on sprint planning    --}}
    <div class="container">
        <div class="row">
            <div class="col-4" id="todo">
            <h3>To Do:</h3>
                        @foreach($planning as $planningitems)
                            <div class="row">
                                <div class="card col-10">
                                    <br>
                                    <div class="card-header">
                                        {{ $planningitems->description }}  {{ $planningitems->deadline }}
                                    </div>
                                    <div class="card-body text-center">
                                        <button class="btn-primary">Next</button>
                                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#removeModal{{$planningitems->id}}">
                                            X
                                        </button>
                                        <div>
                                        </div>
                                        <div class="modal" id="removeModal{{$planningitems ->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Bevestiging</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Weet je zeker dat je <b>{{ $planningitems ->description }}</b> wil verwijderen?
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Sluiten</button>
                                                        <form action="{{url('deleteplanning')}}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            <input type="hidden" name="id" value="{{$planningitems ->id}}">
                                                            <input type="submit" value="Verwijder" class="btn btn-danger">
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br>
                        @endforeach
                    <br>
            </div>
            <div class="col-4" id="progress">
                <h3>In Progress:</h3>
            </div>
            <div class="col-4" id="done">
                <h4>Done:</h4>
            </div>
    </div>
    </div>

@endsection

resources/views/projects/create.blade.php
<?php

resources/views/projects/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Timothy
 * Date: 2-12-2019
 * Time: 11:41
 */

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container text-center"><h4>Mijn projecten</h4></div>
    <div class="container">
        <div class="row justify-content-center">
            @foreach($projects as $project)
                <div class="col-4">
                    <div class="card">
                        <div class="card-header">
                            {{ $project->title }}
                        </div>
                        <div class="card-body">
                            Omschrijving project :{{ $project->description }}
                            <br>
                            Deadline :{{ $project->deadline }}
                        </div>
                    </div>
                    <br>
                </div>
            @endforeach
        </div>
        <br>
        <div class="container">
            <div class="row justify-content-center">
                <div id="paginationEvents" style="text-align: center">
                    <div id="bar">
                        {{ $projects->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{--create project--}}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5">
                <div class="card">
                    <form action="{{ route('project.store') }}" method="post">
                        @csrf
                        <div class="card-header">
                            <a>Naam project </a><input type="text" name="title" placeholder="Scrum" required><br><br>
                            <a>Beschrijving </a><textarea name="description" placeholder="beschrijving project"></textarea>
                            {{--<input type="text" name="activity" required>--}}
                        </div>
                        <div class="card-body">
                            Deadline: <input type="date" name="deadline" placeholder="2020-01-10" required><br><br>
                            <div class="text-center">
                                <input type="submit" value="Maak nieuw project">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{--end create project--}}
@endsection

resources/views/projects/show.blade.php
<?php